// Mock AI service - can be replaced with OpenAI or Gemini
class MockAIService {
    async generateDocument(templateId, fields) {
        await this.delay(1000); // Simulate API call

        return this.generateMockContent(templateId, fields);
    }

    generateMockContent(templateId, fields) {
        const fieldEntries = Object.entries(fields).map(([key, value]) => {
            const label = key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
            return `${label}: ${value}`;
        }).join('\n');

        return `
=== ${templateId.toUpperCase()} ===

This is an AI-generated legal document draft.

DOCUMENT DETAILS:
${fieldEntries}

TERMS AND CONDITIONS:
[This section would contain the full legal document text generated based on the template and provided fields]

1. PARTIES
   The parties to this agreement are as specified above.

2. PURPOSE
   This document serves the purpose as outlined in the provided information.

3. TERMS
   [Detailed terms would be generated here based on the document type and fields]

4. SIGNATURES
   This document requires review and approval by a qualified legal professional before use.

---
Generated by Auto-Legal Drafting System
Date: ${new Date().toISOString()}
Template: ${templateId}
---

NOTE: This is a draft document and must be reviewed by a lawyer before use.
        `.trim();
    }

    delay(ms) {
        return new Promise(resolve => setTimeout(resolve, ms));
    }
}

// OpenAI Service (requires OPENAI_API_KEY in .env)
class OpenAIService {
    constructor() {
        this.apiKey = process.env.OPENAI_API_KEY;
        this.baseURL = 'https://api.openai.com/v1';
    }

    async generateDocument(templateId, fields) {
        const prompt = this.buildPrompt(templateId, fields);

        try {
            const response = await fetch(`${this.baseURL}/chat/completions`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${this.apiKey}`
                },
                body: JSON.stringify({
                    model: 'gpt-4',
                    messages: [
                        {
                            role: 'system',
                            content: 'You are a legal document drafting assistant. Generate clear, professional legal documents based on the provided template and information.'
                        },
                        {
                            role: 'user',
                            content: prompt
                        }
                    ],
                    temperature: 0.7,
                    max_tokens: 2000
                })
            });

            const data = await response.json();
            return data.choices[0].message.content;
        } catch (error) {
            console.error('OpenAI API Error:', error);
            throw new Error('Failed to generate document content');
        }
    }

    buildPrompt(templateId, fields) {
        const fieldsList = Object.entries(fields)
            .map(([key, value]) => `${key}: ${value}`)
            .join('\n');

        return `Generate a professional ${templateId} document with the following details:\n\n${fieldsList}\n\nInclude all necessary legal clauses and format it professionally.`;
    }
}

// Gemini Service (requires GEMINI_API_KEY in .env)
class GeminiService {
    constructor() {
        this.apiKey = process.env.GEMINI_API_KEY;
        this.baseURL = 'https://generativelanguage.googleapis.com/v1beta';
    }

    async generateDocument(templateId, fields) {
        const prompt = this.buildPrompt(templateId, fields);

        try {
            const response = await fetch(
                `${this.baseURL}/models/gemini-pro:generateContent?key=${this.apiKey}`,
                {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({
                        contents: [{
                            parts: [{
                                text: `You are a legal document drafting assistant. ${prompt}`
                            }]
                        }],
                        generationConfig: {
                            temperature: 0.7,
                            maxOutputTokens: 2000
                        }
                    })
                }
            );

            const data = await response.json();
            return data.candidates[0].content.parts[0].text;
        } catch (error) {
            console.error('Gemini API Error:', error);
            throw new Error('Failed to generate document content');
        }
    }

    buildPrompt(templateId, fields) {
        const fieldsList = Object.entries(fields)
            .map(([key, value]) => `${key}: ${value}`)
            .join('\n');

        return `Generate a professional ${templateId} document with the following details:\n\n${fieldsList}\n\nInclude all necessary legal clauses and format it professionally.`;
    }
}

// Factory to get the appropriate AI service based on config
const getAIService = () => {
    const service = process.env.AI_SERVICE || 'mock';

    switch (service) {
        case 'openai':
            return new OpenAIService();
        case 'gemini':
            return new GeminiService();
        case 'mock':
        default:
            return new MockAIService();
    }
};

module.exports = { getAIService };
